version: '2'
services:
  web:
    image: nginx:latest
    ports: 
      - "8080:80"
    volumes:
      - ./SmartHumidor:/src/SmartHumidor
      - ./site.conf:/etc/nginx/conf.d/site.conf
    links:
      - php
  php:
    build:
      context: './build'
    volumes:
      - ./SmartHumidor:/src/SmartHumidor